// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_api.proto

package protobuf_def

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ParamSendDownStreamMsg struct {
	YewuId               string   `protobuf:"bytes,1,opt,name=yewuId,proto3" json:"yewuId,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParamSendDownStreamMsg) Reset()         { *m = ParamSendDownStreamMsg{} }
func (m *ParamSendDownStreamMsg) String() string { return proto.CompactTextString(m) }
func (*ParamSendDownStreamMsg) ProtoMessage()    {}
func (*ParamSendDownStreamMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_6011012888d6542c, []int{0}
}

func (m *ParamSendDownStreamMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParamSendDownStreamMsg.Unmarshal(m, b)
}
func (m *ParamSendDownStreamMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParamSendDownStreamMsg.Marshal(b, m, deterministic)
}
func (m *ParamSendDownStreamMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParamSendDownStreamMsg.Merge(m, src)
}
func (m *ParamSendDownStreamMsg) XXX_Size() int {
	return xxx_messageInfo_ParamSendDownStreamMsg.Size(m)
}
func (m *ParamSendDownStreamMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ParamSendDownStreamMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ParamSendDownStreamMsg proto.InternalMessageInfo

func (m *ParamSendDownStreamMsg) GetYewuId() string {
	if m != nil {
		return m.YewuId
	}
	return ""
}

func (m *ParamSendDownStreamMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ResSendDownStreamMsg struct {
	Status               int32    `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,12,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,13,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResSendDownStreamMsg) Reset()         { *m = ResSendDownStreamMsg{} }
func (m *ResSendDownStreamMsg) String() string { return proto.CompactTextString(m) }
func (*ResSendDownStreamMsg) ProtoMessage()    {}
func (*ResSendDownStreamMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_6011012888d6542c, []int{1}
}

func (m *ResSendDownStreamMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResSendDownStreamMsg.Unmarshal(m, b)
}
func (m *ResSendDownStreamMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResSendDownStreamMsg.Marshal(b, m, deterministic)
}
func (m *ResSendDownStreamMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResSendDownStreamMsg.Merge(m, src)
}
func (m *ResSendDownStreamMsg) XXX_Size() int {
	return xxx_messageInfo_ResSendDownStreamMsg.Size(m)
}
func (m *ResSendDownStreamMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ResSendDownStreamMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ResSendDownStreamMsg proto.InternalMessageInfo

func (m *ResSendDownStreamMsg) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ResSendDownStreamMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResSendDownStreamMsg) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*ParamSendDownStreamMsg)(nil), "protobuf_def.ParamSendDownStreamMsg")
	proto.RegisterType((*ResSendDownStreamMsg)(nil), "protobuf_def.ResSendDownStreamMsg")
}

func init() { proto.RegisterFile("server_api.proto", fileDescriptor_6011012888d6542c) }

var fileDescriptor_6011012888d6542c = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0x8a, 0x4f, 0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x01, 0x53,
	0x49, 0xa5, 0x69, 0xf1, 0x29, 0xa9, 0x69, 0x4a, 0x4e, 0x5c, 0x62, 0x01, 0x89, 0x45, 0x89, 0xb9,
	0xc1, 0xa9, 0x79, 0x29, 0x2e, 0xf9, 0xe5, 0x79, 0xc1, 0x25, 0x45, 0xa9, 0x89, 0xb9, 0xbe, 0xc5,
	0xe9, 0x42, 0x62, 0x5c, 0x6c, 0x95, 0xa9, 0xe5, 0xa5, 0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x50, 0x9e, 0x90, 0x00, 0x17, 0x73, 0x6e, 0x71, 0xba, 0x04, 0x13, 0x58, 0x10, 0xc4,
	0x54, 0x0a, 0xe1, 0x12, 0x09, 0x4a, 0x2d, 0xc6, 0x6a, 0x42, 0x71, 0x49, 0x62, 0x49, 0x69, 0xb1,
	0x04, 0xb7, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x94, 0x07, 0x33, 0x81, 0x07, 0x6e, 0x82, 0x90, 0x10,
	0x17, 0x4b, 0x4a, 0x62, 0x49, 0xa2, 0x04, 0x2f, 0x58, 0x08, 0xcc, 0x36, 0x2a, 0xe6, 0x12, 0x08,
	0x06, 0xbb, 0xdd, 0xb1, 0x20, 0x13, 0xc4, 0xc8, 0x4c, 0x4e, 0x15, 0x8a, 0xe7, 0x12, 0xc4, 0xb4,
	0x46, 0x45, 0x0f, 0xd9, 0x47, 0x7a, 0xd8, 0xbd, 0x23, 0xa5, 0x84, 0xaa, 0x0a, 0x9b, 0x83, 0x95,
	0x18, 0x92, 0xd8, 0xc0, 0x8a, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x23, 0xdd, 0xe2,
	0x37, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerApiServiceClient is the client API for ServerApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerApiServiceClient interface {
	//发送下行消息
	SendDownStreamMsg(ctx context.Context, in *ParamSendDownStreamMsg, opts ...grpc.CallOption) (*ResSendDownStreamMsg, error)
}

type serverApiServiceClient struct {
	cc *grpc.ClientConn
}

func NewServerApiServiceClient(cc *grpc.ClientConn) ServerApiServiceClient {
	return &serverApiServiceClient{cc}
}

func (c *serverApiServiceClient) SendDownStreamMsg(ctx context.Context, in *ParamSendDownStreamMsg, opts ...grpc.CallOption) (*ResSendDownStreamMsg, error) {
	out := new(ResSendDownStreamMsg)
	err := c.cc.Invoke(ctx, "/protobuf_def.ServerApiService/SendDownStreamMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerApiServiceServer is the server API for ServerApiService service.
type ServerApiServiceServer interface {
	//发送下行消息
	SendDownStreamMsg(context.Context, *ParamSendDownStreamMsg) (*ResSendDownStreamMsg, error)
}

// UnimplementedServerApiServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServerApiServiceServer struct {
}

func (*UnimplementedServerApiServiceServer) SendDownStreamMsg(ctx context.Context, req *ParamSendDownStreamMsg) (*ResSendDownStreamMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDownStreamMsg not implemented")
}

func RegisterServerApiServiceServer(s *grpc.Server, srv ServerApiServiceServer) {
	s.RegisterService(&_ServerApiService_serviceDesc, srv)
}

func _ServerApiService_SendDownStreamMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamSendDownStreamMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerApiServiceServer).SendDownStreamMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf_def.ServerApiService/SendDownStreamMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerApiServiceServer).SendDownStreamMsg(ctx, req.(*ParamSendDownStreamMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf_def.ServerApiService",
	HandlerType: (*ServerApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendDownStreamMsg",
			Handler:    _ServerApiService_SendDownStreamMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server_api.proto",
}
